--------------------------------------------------------
-- Archivo creado  - domingo-diciembre-14-2014   
--------------------------------------------------------
DROP TABLE "ARTICULOS" cascade constraints;
DROP TABLE "CLIENTES" cascade constraints;
DROP TABLE "PEDIDOS" cascade constraints;
DROP TABLE "PEDIDOSARTICULOS" cascade constraints;
DROP TABLE "TIPOCAMBIO" cascade constraints;
DROP TABLE "USUARIOS" cascade constraints;
DROP TABLE "ROLES" cascade constraints;
DROP TABLE "PROVEEDORES" cascade constraints;
DROP TABLE "PROVEEDORARTICULOS" cascade constraints;
DROP TABLE "HISTORIALCAMBIOS" cascade constraints;
DROP TABLE "MEDIDAS" cascade constraints;
DROP TABLE "COMPOSICIONES" cascade constraints;
DROP TABLE "FORMASDEPAGO" cascade constraints;
DROP TABLE "ESTADOS" cascade constraints;

  CREATE TABLE "MEDIDAS" 
   (	"IDMEDIDA" NUMBER(5) primary key, 
	"MEDIDA" VARCHAR2(40 BYTE)
   );
REM INSERTING into MEDIDAS
SET DEFINE OFF;
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('1','80 x 180 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('2','80 x 190 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('3','80 x 200 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('4','90 x 180 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('5','90 x 190 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('6','90 x 200 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('7','105 x 180 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('8','105 x 190 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('9','105 x 200 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('10','135 x 180 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('11','135 x 190 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('12','135 x 200 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('13','150 x 180 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('14','150 x 190 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('15','150 x 200 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('19','Talla S');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('21','Talla L');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('20','Talla M');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('22','Talla XL');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('16','90 x 35 x 100 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('17','100 x 40 x 100 cm');
Insert into MEDIDAS (IDMEDIDA,MEDIDA) values ('18','120 x 35 x 110 cm');

commit;
--------------------------------------------------------
--  DDL for Table COMPOSICIONES
--------------------------------------------------------

  CREATE TABLE "COMPOSICIONES" 
   (	"IDCOMPOSICION" NUMBER(5) primary key, 
	"COMPOSICION" VARCHAR2(40 BYTE)
   );
REM INSERTING into COMPOSICIONES
SET DEFINE OFF;
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('11','Algodon');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('1','Poliester');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('4','Muelles');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('5','Viscoelástica');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('3','Latex');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('2','Enrollado');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('6','Franela');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('7','Raso');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('8','Madera');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('9','Aglomerado');
Insert into COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('10','Metálico');

commit;
  CREATE TABLE "ARTICULOS" 
   ("IDARTICULO" NUMBER(5) primary key , 
	"REFCOMPOSICION" NUMBER(5), 
	"REFMEDIDA" NUMBER(5), 
	"PRECIO" NUMBER(8,2), 
	"ELIMINADO" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"REFERENCIA" NUMBER
   );

   COMMENT ON COLUMN "ARTICULOS"."ELIMINADO" IS '0: NO ELIMINADO 1: ELIMINADO ';
   COMMENT ON COLUMN "ARTICULOS"."STOCK" IS 'CANTIDAD ARTICULO';
   
REM INSERTING into ARTICULOS
SET DEFINE OFF;
Insert into ARTICULOS values ('1','11','11','25,99','0','SÁBANA BAJERA','1234');
Insert into ARTICULOS values ('11','7','10','25,5','0','SÁBANAS BLANCAS','1244');
Insert into ARTICULOS values ('12','5','13','450,9','0','COLCHÓN','1245');
Insert into ARTICULOS values ('6','11','11','15,95','0','SÁBANAS DE CUADROS','1239');
Insert into ARTICULOS values ('7','8','8','255,99','0','CAMA','1240');
Insert into ARTICULOS values ('8','9','9','120,5','0','SOMIER','1241');
Insert into ARTICULOS values ('13','8','17','35,5','0','MESA ENTRADA','1246');
Insert into ARTICULOS values ('14','9','16','30,9','0','ZAPATERO','1247');
Insert into ARTICULOS values ('15','2','7','15','1','SÁBANAS DE FRANELA','1285');
Insert into ARTICULOS values ('2','3','3','24,5','0','ALMOHADA','1235');
Insert into ARTICULOS values ('3','5','5','105,5','0','COLCHÓN PIKOLIN','1236');
Insert into ARTICULOS values ('4','5','5','82,9','0','LO MONACO','1237');
Insert into ARTICULOS values ('5','3','3','120,45','0','NORMABLOCK','1238');
Insert into ARTICULOS values ('9','11','17','19,95','0','PIJAMA DE SNOOPY','1242');
Insert into ARTICULOS values ('10','11','9','22,5','0','SÁBANAS DE RALLAS','1243');


create table compuestos(
  idcompuesto number(3) primary key,
  nombre varchar2(50),
  precio number(8,2),
  eliminado number(1)
);

CREATE TABLE "ARTICULOSPARTES" (	
    "IDARTICULOPARTES" NUMBER(5,0) primary key, 
	"IDCOMPUESTO" NUMBER(5,0), 
	"IDARTICULO" NUMBER(5,0), 
	"CANTIDAD" NUMBER(3,0)
    constraint fk_idCompuesto foreign key (idcompuesto) references COMPUESTOS(idcompuesto)
   );


create table articulosstock(
 idstock number(5) primary key,
 idarticulo number(5),
 stockreal number(5),
 stockideal number(5),
 foreign key (idarticulo) references ARTICULOS(idarticulo)
);

--------------------------------------------------------
-- Archivo creado  - jueves-febrero-05-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ESTADOS
--------------------------------------------------------

  CREATE TABLE "ESTADOS" 
   (	"IDESTADO" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"ACTIVO" CHAR(1 BYTE)
   );

   COMMENT ON COLUMN "ESTADOS"."ACTIVO" IS '''S'' o ''N''';
REM INSERTING into genESTADOS
SET DEFINE OFF;
Insert into ESTADOS (IDESTADO,NOMBRE,ACTIVO) values ('1','CONFIRMADO','N');
Insert into ESTADOS (IDESTADO,NOMBRE,ACTIVO) values ('2','ETIQUETADO','N');
Insert into ESTADOS (IDESTADO,NOMBRE,ACTIVO) values ('3','ENVIADO','N');
Insert into ESTADOS (IDESTADO,NOMBRE,ACTIVO) values ('4','FACTURADO','N');
Insert into ESTADOS (IDESTADO,NOMBRE,ACTIVO) values ('5','NINGUNO','N');
--------------------------------------------------------
--  DDL for Index ESTADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTADOS_PK" ON "ESTADOS" ("IDESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ESTADOS
--------------------------------------------------------

  ALTER TABLE "ESTADOS" MODIFY ("IDESTADO" NOT NULL ENABLE);
  ALTER TABLE "ESTADOS" ADD CONSTRAINT "ESTADOS_PK" PRIMARY KEY ("IDESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  
  commit;


--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "CLIENTES" 
   (	"IDCLIENTE" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER(5,0), 
	"TELEFONO" NUMBER(9,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ELIMINADO" NUMBER(1,0), 
	"DNI" VARCHAR2(9 BYTE)
   );

Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('4','Carlos','del Cerro','Escudero','Calle secreta','1540','987456321','yomolo@yaves.com','0','05693819P');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('5','Noemi','La coba','Me lo invento','En algún lugar','49729','987526417',null,'0','04324521Z');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('1','Luis','Colmero','Rabadon','C/Zarza parrilla 2º','1462','986523417','parrilla@yahoo.es','0','02541365A');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('3','Palomino','mendoza','Peregrino','Azotea Alta','29','987456321','yaack@gas.com','0','05312578B');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('2','Filipe','Segunda','Mano','al sur','30','956321478','email@email.com','0','05641238A');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('6','Raquel','Mansilla','Herencia','C/Alemania 32','14764','926220085','raquel@hotmail.com','0','05683420M');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('7','Javier','rtedrdef','dfgbhfd','Prueba de ','-1','96525856',null,'0','05699254S');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('10','Luis','Ayuga','Profesor','Real','49729','956545454','luis@gmail.com','0','05710881G');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('8','Eduardo','Mansilla','Herencia','Calle Nueva','14763','679334455',null,'0','05683421Y');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('9','Juan','Perez','Sanchez','Calle Encina','18472','914324477',null,'0','03423423B');

--------------------------------------------------------
--  DDL for Table TIPOCAMBIO
--------------------------------------------------------

  CREATE TABLE "TIPOCAMBIO" 
   ("IDTIPOCAMBIO" NUMBER(4,0), 
	"DESCRIPCION" VARCHAR2(40 BYTE)
   );
   
REM INSERTING into TIPOCAMBIO
SET DEFINE OFF;
Insert into TIPOCAMBIO values ('1','Añadido');
Insert into TIPOCAMBIO values ('2','Modificado');
Insert into TIPOCAMBIO values ('3','Borrado');
Insert into TIPOCAMBIO values ('4','Restaurar');
insert into tipocambio values(5,'Liquidado');
insert into tipocambio values(6,'No liquidado');
insert into tipocambio values(7,'Anulado');
insert into tipocambio values (8,'Liquidada parcialmente');
   
--------------------------------------------------------
--  DDL for Table PEDIDOS
--------------------------------------------------------

  CREATE TABLE "PEDIDOS" 
   ("IDPEDIDO" NUMBER(5,0), 
	"REFCLIENTE" NUMBER, 
	"REFUSUARIO" NUMBER(3,0), 
	"FECHA" NUMBER(8,0), 
	"REFFORMAPAGO" NUMBER, 
	"TOTAL" NUMBER(8,2), 
	"LIQUIDADO" CHAR(1 BYTE), 
	"N_PEDIDO" NUMBER, 
	"ELIMINADO" NUMBER, 
	"IDESTADO" NUMBER(3,0), 
	"IMPORTEPAGADO" NUMBER(8,2),
	foreign key (idestado) references ESTADOS(idestado)
   );

   COMMENT ON COLUMN "PEDIDOS"."LIQUIDADO" IS 'N o S';
   COMMENT ON COLUMN "PEDIDOS"."IMPORTEPAGADO" IS 'N o S';
--------------------------------------------------------
--  DDL for Table PEDIDOSARTICULOS
--------------------------------------------------------

  CREATE TABLE "PEDIDOSARTICULOS" 
   ("IDPEDIDOARTICULO" NUMBER(5,0), 
	"REFPEDIDO" NUMBER(5,0), 
	"REFARTICULO" NUMBER(5), 
	"CANTIDAD" NUMBER(3), 
	"PRECIOVENTA" NUMBER(8,2)
   );

--------------------------------------------------------
--  DDL for Table PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "PROVEEDORES" 
   (	"IDPROVEEDOR" NUMBER(5,0), 
	"CIF" VARCHAR2(9 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER(5,0), 
	"TELEFONO" NUMBER(9,0), 
	"ELIMINADO" NUMBER(1,0), 
	"NIF" VARCHAR2(9 BYTE), 
	"MOVIL" NUMBER(9,0), 
	"PAIS" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"CONTACTO" VARCHAR2(50 BYTE), 
	"OBSERVACIONES" VARCHAR2(120 BYTE)
   );
REM INSERTING into PROVEEDORES
SET DEFINE OFF;
Insert into PROVEEDORES (IDPROVEEDOR,CIF,NOMBRE,DIRECCION,REFCPPOBLACIONES,TELEFONO,ELIMINADO,NIF,MOVIL,PAIS,EMAIL,CONTACTO,OBSERVACIONES) values ('2','A12389128','Cosas de casa','Real','4678','921231231','0','-','987654321','España','-','Juan','-');
Insert into PROVEEDORES (IDPROVEEDOR,CIF,NOMBRE,DIRECCION,REFCPPOBLACIONES,TELEFONO,ELIMINADO,NIF,MOVIL,PAIS,EMAIL,CONTACTO,OBSERVACIONES) values ('3','J73580904','Remigio Colchas','Las eras','2216','939393939','0','-','694433222','-','-','Remigio','hablar con manolo carretillas');
Insert into PROVEEDORES (IDPROVEEDOR,CIF,NOMBRE,DIRECCION,REFCPPOBLACIONES,TELEFONO,ELIMINADO,NIF,MOVIL,PAIS,EMAIL,CONTACTO,OBSERVACIONES) values ('1','-','Robustiano','Manzana','3035','923123123','0','04237426S','987654321','España','-','-','-');
Insert into PROVEEDORES (IDPROVEEDOR,CIF,NOMBRE,DIRECCION,REFCPPOBLACIONES,TELEFONO,ELIMINADO,NIF,MOVIL,PAIS,EMAIL,CONTACTO,OBSERVACIONES) values ('4','-','Jacinto','Los montes','4463','926554433','0','05683420M','0','España','-','-','-');
Insert into PROVEEDORES (IDPROVEEDOR,CIF,NOMBRE,DIRECCION,REFCPPOBLACIONES,TELEFONO,ELIMINADO,NIF,MOVIL,PAIS,EMAIL,CONTACTO,OBSERVACIONES) values ('5','-','Manolin','Valladolid','30','987456123','0','05693819P','0','España','-','-','-');
--------------------------------------------------------
--  DDL for Index SYS_C007343
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007343" ON "PROVEEDORES" ("IDPROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "PROVEEDORES" ADD PRIMARY KEY ("IDPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
---------------------------------------
--- TABLA ARTICULOS DE PROVEEDOR   ----
---------------------------------------
  CREATE TABLE "PROVEEDORARTICULOS"
   (    "IDPROVEEDORARTICULO" NUMBER(5,0),
    "IDPROVEEDOR" NUMBER(5,0),
    "IDARTICULO" NUMBER(5,0),
    "NOMBREPROVEEDOR" VARCHAR2(30 BYTE),
    "PRECIOPROVEEDOR" NUMBER(6,2),
    "ELIMINADO" NUMBER(1,0)
   );
--------------------------------------------------------
--  DDL for Index PROVEEDORARTICULOS_PK
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PROVEEDORARTICULOS_PK" ON "PROVEEDORARTICULOS" ("IDPROVEEDORARTICULO");
--------------------------------------------------------
--  Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------
 
  ALTER TABLE "PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_PK" PRIMARY KEY ("IDPROVEEDORARTICULO");
  ALTER TABLE "PROVEEDORARTICULOS" MODIFY ("IDPROVEEDORARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------
 
  ALTER TABLE "PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_FK1" FOREIGN KEY ("IDARTICULO")
      REFERENCES "ARTICULOS" ("IDARTICULO") ENABLE;
  ALTER TABLE "PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_FK2" FOREIGN KEY ("IDPROVEEDOR")
      REFERENCES "PROVEEDORES" ("IDPROVEEDOR") ENABLE;
	  
commit;


--------------------------------------------------------
--  DDL for Table FACTURAS
--------------------------------------------------------

  CREATE TABLE "FACTURAS" 
   (	"IDFACTURA" NUMBER(5,0), 
	"NUMFACTURA" NUMBER(8,0), 
	"IDCLIENTE" NUMBER(5,0), 
	"IDPEDIDO" NUMBER(5,0), 
	"FECHA" NUMBER(8,0), 
	"HORA" NUMBER(6,0), 
	"IMPORTENETO" NUMBER(8,2), 
	"ELIMINADO" NUMBER(1,0), 
	"CONTABILIZADA" CHAR(1 BYTE)
   );
--------------------------------------------------------
--  DDL for Index FACTURAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FACTURAS_PK" ON "FACTURAS" ("IDFACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FACTURAS
--------------------------------------------------------

  ALTER TABLE "FACTURAS" ADD CONSTRAINT "FACTURAS_PK" PRIMARY KEY ("IDFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FACTURAS" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
  ALTER TABLE "FACTURAS" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "FACTURAS" MODIFY ("NUMFACTURA" NOT NULL ENABLE);
  ALTER TABLE "FACTURAS" MODIFY ("IDFACTURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FACTURAS
--------------------------------------------------------

  ALTER TABLE "FACTURAS" ADD CONSTRAINT "FACTURAS_FK1" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "CLIENTES" ("IDCLIENTE") ENABLE;
	  
commit;


--------------------------------------------------------
--  DDL for Table FACTURASARTICULOS
--------------------------------------------------------

  CREATE TABLE "FACTURASARTICULOS" 
   (	"IDFACTURAARTICULOS" NUMBER(3,0), 
	"NUMFACTURA" NUMBER(8,0), 
	"IDCLIENTE" NUMBER(5,0), 
	"FECHA" NUMBER(8,0), 
	"HORA" NUMBER(6,0), 
	"IMPORTENETO" NUMBER(8,2), 
	"CONTABILIZADA" CHAR(1 BYTE), 
	"ELIMINADA" NUMBER(1,0),
	"IDFACTURA" NUMBER(5,0)
   );
--------------------------------------------------------
--  DDL for Index SYS_C007580
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007580" ON "FACTURASARTICULOS" ("IDFACTURAARTICULOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FACTURASARTICULOS
--------------------------------------------------------

  ALTER TABLE "FACTURASARTICULOS" ADD PRIMARY KEY ("IDFACTURAARTICULOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURASARTICULOS
--------------------------------------------------------

  ALTER TABLE "FACTURASARTICULOS" ADD FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "CLIENTES" ("IDCLIENTE") ENABLE;


--------------------------------------------------------
--  DDL for Table ARTICULOSGENERICOS
--------------------------------------------------------

  CREATE TABLE "ARTICULOSGENERICOS" 
   (	"IDARTICULOGENERICO" NUMBER(3,0), 
	"IDFACTURAARTICULOS" NUMBER(3,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"PRECIO" NUMBER(8,2), 
	"CANTIDAD" NUMBER(3,0), 
	"ELIMINADA" NUMBER(1,0)
   );
--------------------------------------------------------
--  DDL for Index SYS_C007582
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007582" ON "ARTICULOSGENERICOS" ("IDARTICULOGENERICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ARTICULOSGENERICOS
--------------------------------------------------------

  ALTER TABLE "ARTICULOSGENERICOS" ADD PRIMARY KEY ("IDARTICULOGENERICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARTICULOSGENERICOS
--------------------------------------------------------

  ALTER TABLE "ARTICULOSGENERICOS" ADD FOREIGN KEY ("IDFACTURAARTICULOS")
	  REFERENCES "FACTURASARTICULOS" ("IDFACTURAARTICULOS") ENABLE;

--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ROLES" 
   (	"IDROL" NUMBER(1,0), 
	"NOMBREROL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ROLES"."IDROL" IS 'IDENTIFICgenOR DEL ROL';
REM INSERTING into ROLES
SET DEFINE OFF;
Insert into ROLES (IDROL,NOMBREROL) values ('1','ROOT');
Insert into ROLES (IDROL,NOMBREROL) values ('2','ADMINISTRATIVO');
Insert into ROLES (IDROL,NOMBREROL) values ('3','OPERATIVO');
Insert into ROLES (IDROL,NOMBREROL) values ('4','CONTABLE');
  
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "USUARIOS" 
   ("IDUSUARIO" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(150 BYTE), 
	"ELIMINADO" NUMBER(1,0), 
	"IDROL" NUMBER(3,0)
   );

   COMMENT ON COLUMN "USUARIOS"."IDUSUARIO" IS 'IDENTIFICgenOR DEL USUARIO';
   COMMENT ON COLUMN "USUARIOS"."NOMBRE" IS 'NOMBRE DEL USUARIO';
   COMMENT ON COLUMN "USUARIOS"."PASSWORD" IS 'CONTRASEÑA DE ACCESO';
   COMMENT ON COLUMN "USUARIOS"."ELIMINADO" IS '0 -> NO ELIMINADO 1-> ELIMINADO';
   COMMENT ON COLUMN "USUARIOS"."IDROL" IS 'PERMISOS DEL USUARIO';
   

REM INSERTING into USUARIOS
SET DEFINE OFF;
Insert into USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('4','Luis','$2a$10$woQp6bc2w3UgMrbSftRImuOUlzV/sX62u9y9eJi.vWpA3S.quJwne','0','2');
Insert into USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('2','Carlos','$2a$10$JIXWxPhIKHs/Q/P7es/wKuhzk9T7UhP9kubPZEUfDiTNNL0BiWVJ6','1','2');
Insert into USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('3','Noemi','$2a$10$e2g3pVj6bZhB3XBo4D.WxOJYEcMofMA6fkpwA2uAU43G089Coy0RG','1','3');
Insert into USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('1','ROOT','$2a$10$o15Ks1bfPYTpWaCvXPqgTOnoxi9wGP9EafD4IyfFB6vGl1Hh4Nq6K','0','1');
Insert into USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('5','hola','$2a$10$.Bq7z7/YdlZ/YDcnGkQ9summ.vp.j/lOdDLd/sukV79YtE/YVfTpC','0','3');
Insert into USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('6','usuario','$2a$10$Ucmz7bCpOWT49Kdiiw/A0umgwPkb3Z.TvgWZRdLy1yVUix3QIjb96','0','3');

--------------------------------------------------------
--  DDL for Table HISTORIALCAMBIOS
--------------------------------------------------------

  CREATE TABLE "HISTORIALCAMBIOS" 
   (	"IDHISTOCAMBIO" NUMBER(4,0), 
	"IDUSUARIO" NUMBER(3,0), 
	"FECHA" VARCHAR2(20 BYTE), 
	"IDTIPOCAMBIO" NUMBER(4,0), 
	"OBSERVACION" VARCHAR2(50 BYTE)
   );

--------------------------------------------------------
--  DDL for Table FORMASDEPAGO
--------------------------------------------------------

  CREATE TABLE "FORMASDEPAGO" 
   (	"IDPAGO" NUMBER(3,0), 
	"FORMAPAGO" VARCHAR2(100 BYTE), 
	"ACTIVO" NUMBER(1,0)
   );
 

   COMMENT ON COLUMN "FORMASDEPAGO"."IDPAGO" IS 'IDENTIFICADOR DE LA FORMA DE PAGO';
 
   COMMENT ON COLUMN "FORMASDEPAGO"."ACTIVO" IS '0 -> NO ACTIVO 1-> ACTIVO
';
REM INSERTING into FORMASDEPAGO
SET DEFINE OFF;
Insert into FORMASDEPAGO (IDPAGO,FORMAPAGO,ACTIVO) values ('1','EFECTIVO','1');
Insert into FORMASDEPAGO (IDPAGO,FORMAPAGO,ACTIVO) values ('2','CONTRAREEMBOLSO','1');
Insert into FORMASDEPAGO (IDPAGO,FORMAPAGO,ACTIVO) values ('3','TARJETA','1');
Insert into FORMASDEPAGO (IDPAGO,FORMAPAGO,ACTIVO) values ('4','PAYPAL','1');
Insert into FORMASDEPAGO (IDPAGO,FORMAPAGO,ACTIVO) values ('5','TRANSFERENCIA','1');


--------------------------------------------------------
--  DDL for Index ARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARTICULOS_PK" ON "ARTICULOS" ("IDARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIENTES_PK" ON "CLIENTES" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEDIDOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PEDIDOS_PK" ON "PEDIDOS" ("IDPEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEDIDOSARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PEDIDOSARTICULOS_PK" ON "PEDIDOSARTICULOS" ("IDPEDIDOARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPOCAMBIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPOCAMBIO_PK" ON "TIPOCAMBIO" ("IDTIPOCAMBIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIOS_PK" ON "USUARIOS" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROLES_PK" ON "ROLES" ("IDROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEEDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROVEEDORES_PK" ON "PROVEEDORES" ("IDPROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEEDORARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROVEEDORARTICULOS_PK" ON "PROVEEDORARTICULOS" ("IDPROVART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HISTORIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HISTORIAL_PK" ON "HISTORIALCAMBIOS" ("IDHISTOCAMBIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010011
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010011" ON "MEDIDAS" ("IDMEDIDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010010
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010010" ON "COMPOSICIONES" ("IDCOMPOSICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARTICULOS
--------------------------------------------------------

  ALTER TABLE "ARTICULOS" ADD CONSTRAINT "ARTICULOS_PK" PRIMARY KEY ("IDARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ARTICULOS" MODIFY ("IDARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLIENTES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "PEDIDOS_PK" PRIMARY KEY ("IDPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PEDIDOS" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEDIDOSARTICULOS
--------------------------------------------------------

  ALTER TABLE "PEDIDOSARTICULOS" ADD CONSTRAINT "PEDIDOSARTICULOS_PK" PRIMARY KEY ("IDPEDIDOARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PEDIDOSARTICULOS" MODIFY ("IDPEDIDOARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOCAMBIO
--------------------------------------------------------

  ALTER TABLE "TIPOCAMBIO" ADD CONSTRAINT "TIPOCAMBIO_PK" PRIMARY KEY ("IDTIPOCAMBIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TIPOCAMBIO" MODIFY ("IDTIPOCAMBIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USUARIOS" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ROLES" MODIFY ("NOMBREROL" NOT NULL ENABLE);
  ALTER TABLE "ROLES" MODIFY ("IDROL" NOT NULL ENABLE);
  ALTER TABLE "ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("IDROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "PROVEEDORES" MODIFY ("IDPROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "PROVEEDORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PROVEEDORES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "PROVEEDORES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
  ALTER TABLE "PROVEEDORES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "PROVEEDORES" ADD CONSTRAINT "PROVEEDORES_PK" PRIMARY KEY ("IDPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------

  ALTER TABLE "PROVEEDORARTICULOS" MODIFY ("IDPROVART" NOT NULL ENABLE);
  ALTER TABLE "PROVEEDORARTICULOS" MODIFY ("REFPROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "PROVEEDORARTICULOS" MODIFY ("REFARTICULO" NOT NULL ENABLE);
  ALTER TABLE "PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_PK" PRIMARY KEY ("IDPROVART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIALCAMBIOS
--------------------------------------------------------

  ALTER TABLE "HISTORIALCAMBIOS" MODIFY ("IDHISTOCAMBIO" NOT NULL ENABLE);
  ALTER TABLE "HISTORIALCAMBIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "HISTORIALCAMBIOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "HISTORIALCAMBIOS" MODIFY ("IDTIPOCAMBIO" NOT NULL ENABLE);
  ALTER TABLE "HISTORIALCAMBIOS" MODIFY ("OBSERVACION" NOT NULL ENABLE);
  ALTER TABLE "HISTORIALCAMBIOS" ADD CONSTRAINT "HISTORIAL_PK" PRIMARY KEY ("IDHISTOCAMBIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDIDAS
--------------------------------------------------------

  ALTER TABLE "MEDIDAS" ADD PRIMARY KEY ("IDMEDIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPOSICIONES
--------------------------------------------------------

  ALTER TABLE "COMPOSICIONES" ADD PRIMARY KEY ("IDCOMPOSICION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "PEDIDOS_FK1" FOREIGN KEY ("REFUSUARIO")
	  REFERENCES "USUARIOS" ("IDUSUARIO") ENABLE;
  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "PEDIDOS_FPAGO" FOREIGN KEY ("REFFORMAPAGO")
	  REFERENCES "FORMASDEPAGO" ("IDPAGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOSARTICULOS
--------------------------------------------------------

  ALTER TABLE "PEDIDOSARTICULOS" ADD CONSTRAINT "PEDIDOSARTICULOS_ARTICULO" FOREIGN KEY ("REFARTICULO")
	  REFERENCES "ARTICULOS" ("IDARTICULO") ENABLE;
  ALTER TABLE "PEDIDOSARTICULOS" ADD CONSTRAINT "PEDIDOSARTICULOS_PEDIDO" FOREIGN KEY ("REFPEDIDO")
	  REFERENCES "PEDIDOS" ("IDPEDIDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------

  ALTER TABLE "PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_FK2" FOREIGN KEY ("REFPROVEEDOR")
	  REFERENCES "PROVEEDORES" ("IDPROVEEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORIALCAMBIOS
--------------------------------------------------------

  ALTER TABLE "HISTORIALCAMBIOS" ADD CONSTRAINT "HISTORIALCAMBIOS_FK1" FOREIGN KEY ("IDHISTOCAMBIO")
	  REFERENCES "HISTORIALCAMBIOS" ("IDHISTOCAMBIO") ENABLE;

alter table usuarios add primary key (idusuario);
alter table historialcambios modify observacion varchar2(80);
alter table proveedores add primary key(idproveedor);

create table Operaciones(
  idOperacion number(5,0) primary key,
  idprocdest number(3,0),
  tipo varchar2(30),
  concepto varchar2(100),
  importe number(6,2),
  fecha number(8,0),
  hora number(6,0),
  idusuario number(3,0),
  tipoOperacion char(1),--'E -> entrada S -> Salida'
  foreign key (idusuario) references USUARIOS(idusuario)
);

create table validaciones(
  idvalidacion number(5,0) primary key,
  fecha number(8),
  hora number(6), 
  saldototal number(6,2),
  usuario number(3,0),
  foreign key (usuario) references USUARIOS(idusuario)
);

create table procedencias(
	idProcedencia number(3) primary key,
	procedencia varchar(30)
);
insert into procedencias values(1, 'Venta de productos');
insert into procedencias values(2, 'Ingreso directo administrativo');
insert into procedencias values(3, 'Variación de saldo');
insert into procedencias values(4, 'Varios');

create table destinos(
	idDestino number(3) primary key,
	destino varchar(30)
);

insert into destinos values(1,'Gastos de personal');
insert into destinos values(2,'Compras de mercaderías');
insert into destinos values(3,'Retirada de efectivo');
insert into destinos values(4,'Variación de saldo');
insert into destinos values(5,'Varios');

--------------------------------------------------------
--  DDL for Table DEUDAS
--------------------------------------------------------

  CREATE TABLE "DEUDAS" 
   (	"IDDEUDA" NUMBER(3,0), 
	"IDUSUARIO" NUMBER(3,0), 
	"IDPROVEEDOR" NUMBER(5,0), 
	"HORA" NUMBER(6,0), 
	"FECHA" NUMBER(8,0), 
	"IMPORTEPAGADO" NUMBER(8,2), 
	"CONCEPTO" VARCHAR2(100 BYTE), 
	"LIQUIDADA" CHAR(1 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"IMPORTETOTAL" NUMBER(8,2)
   );
--------------------------------------------------------
--  DDL for Index SYS_C007479
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007479" ON "DEUDAS" ("IDDEUDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DEUDAS
--------------------------------------------------------

  ALTER TABLE "DEUDAS" ADD PRIMARY KEY ("IDDEUDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEUDAS
--------------------------------------------------------

  ALTER TABLE "DEUDAS" ADD FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "USUARIOS" ("IDUSUARIO") ENABLE;
  ALTER TABLE "DEUDAS" ADD FOREIGN KEY ("IDPROVEEDOR")
	  REFERENCES "PROVEEDORES" ("IDPROVEEDOR") ENABLE;


CREATE TABLE AGENCIAS 
(IDAGENCIA NUMBER(3, 0) NOT NULL 
, NOMBRE VARCHAR2(40 BYTE) 
, CONSTRAINT AGENCIAS_PK PRIMARY KEY 
  (IDAGENCIA)USING INDEX 
  (CREATE UNIQUE INDEX AGENCIAS_PK ON AGENCIAS (IDAGENCIA ASC) 
      LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 NOPARALLEL ENABLE) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE 
(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT );

insert into agencias values (0, 'NINGUNO');
insert into agencias values (1, 'SEUR');
insert into agencias values (2, 'TOURLINE EXPRESS');
insert into agencias values (3, 'DHL');
insert into agencias values (4, 'OTROS');

CREATE TABLE PENDIENTES 
(
  IDPENDIENTE NUMBER(3, 0) NOT NULL 
, IDUSUARIO NUMBER(3, 0) 
, IDCLIENTE NUMBER(5, 0) 
, IDAGENCIA NUMBER(3, 0) 
, HORA NUMBER(6, 0) 
, FECHA NUMBER(8, 0) 
, IMPORTETOTAL NUMBER(8, 2) 
, IMPORTEPAGADO NUMBER(8, 2) 
, TIPO VARCHAR2(30 BYTE) 
, CONCEPTO VARCHAR2(100 BYTE) 
, LIQUIDADA CHAR(1 BYTE) 
, CONSTRAINT PEND_PK PRIMARY KEY 
  (IDPENDIENTE)USING INDEX(CREATE UNIQUE INDEX TABLE1_PK1 ON PENDIENTES (IDPENDIENTE ASC) 
      LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 NOPARALLEL )ENABLE) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE 
	  (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT );

ALTER TABLE PENDIENTES ADD CONSTRAINT PEND_FK1 FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO) ON DELETE CASCADE ENABLE;
ALTER TABLE PENDIENTES ADD CONSTRAINT PEND_FK2 FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE) ON DELETE CASCADE ENABLE;
ALTER TABLE PENDIENTES ADD CONSTRAINT PEND_FK3 FOREIGN KEY (IDAGENCIA) REFERENCES AGENCIAS(IDAGENCIA) ON DELETE CASCADE ENABLE;

drop articulospartes cascade constraints;
drop compuestos cascade constraints;
--------------------------------------------------------
-- Archivo creado  - sábado-febrero-28-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTICULOSPARTES
--------------------------------------------------------

  CREATE TABLE "ARTICULOSPARTES" 
   (	"IDARTICULOPARTES" NUMBER(5,0), 
	"IDCOMPUESTO" NUMBER(5,0), 
	"IDARTICULO" NUMBER(5,0), 
	"CANTIDAD" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ARTICULOSPARTES
SET DEFINE OFF;
Insert into ARTICULOSPARTES (IDARTICULOPARTES,IDCOMPUESTO,IDARTICULO,CANTIDAD) values ('1','1','2','1');
Insert into ARTICULOSPARTES (IDARTICULOPARTES,IDCOMPUESTO,IDARTICULO,CANTIDAD) values ('2','1','15','2');
--------------------------------------------------------
--  DDL for Index SYS_C007685
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007685" ON "ARTICULOSPARTES" ("IDARTICULOPARTES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ARTICULOSPARTES
--------------------------------------------------------

  ALTER TABLE "ARTICULOSPARTES" ADD PRIMARY KEY ("IDARTICULOPARTES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARTICULOSPARTES
--------------------------------------------------------

  ALTER TABLE "ARTICULOSPARTES" ADD FOREIGN KEY ("IDARTICULO")
	  REFERENCES "ARTICULOS" ("IDARTICULO") ENABLE;
  ALTER TABLE "ARTICULOSPARTES" ADD FOREIGN KEY ("IDCOMPUESTO")
	  REFERENCES "ARTICULOS" ("IDARTICULO") ENABLE;

	  --------------------------------------------------------
-- Archivo creado  - sábado-febrero-28-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPUESTOS
--------------------------------------------------------

  CREATE TABLE "COMPUESTOS" 
   (	"IDCOMPUESTO" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"PRECIO" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into COMPUESTOS
SET DEFINE OFF;
Insert into COMPUESTOS (IDCOMPUESTO,NOMBRE,PRECIO) values ('1','LOTE DUERME CALIENTE','40');
--------------------------------------------------------
--  DDL for Index SYS_C007690
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007690" ON "COMPUESTOS" ("IDCOMPUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMPUESTOS
--------------------------------------------------------

  ALTER TABLE "COMPUESTOS" ADD PRIMARY KEY ("IDCOMPUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

  --------------------------------------------------------
-- Archivo creado  - domingo-marzo-08-2015   
--------------------------------------------------------
DROP TABLE "HISTORIALSTOCK" cascade constraints;
--------------------------------------------------------
--  DDL for Table HISTORIALSTOCK
--------------------------------------------------------

  CREATE TABLE "HISTORIALSTOCK" 
   (	"IDHISTORIAL" NUMBER(5,0), 
	"FECHA" NUMBER(8,0), 
	"IDARTICULO" NUMBER(5,0), 
	"STOCKREAL" NUMBER(5,0), 
	"STOCKIDEAL" NUMBER(5,0), 
	"HORA" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HISTORIALSTOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HISTORIALSTOCK_PK" ON "HISTORIALSTOCK" ("IDHISTORIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HISTORIALSTOCK
--------------------------------------------------------

  ALTER TABLE "HISTORIALSTOCK" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "HISTORIALSTOCK" ADD CONSTRAINT "HISTORIALSTOCK_PK" PRIMARY KEY ("IDHISTORIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISTORIALSTOCK" MODIFY ("IDARTICULO" NOT NULL ENABLE);
  ALTER TABLE "HISTORIALSTOCK" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "HISTORIALSTOCK" MODIFY ("IDHISTORIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HISTORIALSTOCK
--------------------------------------------------------

  ALTER TABLE "HISTORIALSTOCK" ADD CONSTRAINT "HISTORIALSTOCK_FK1" FOREIGN KEY ("IDARTICULO")
	  REFERENCES "ARTICULOS" ("IDARTICULO") ON DELETE CASCADE ENABLE;